twilio: # Twilio gateway configuration
  accountId: ACc16ed4b4b149614fc3cb9da0146c65bb
  accountToken: 709cc3e93e5be6fbdec1b8e4fa6cc846
  #nanpaMessagingServiceSid: # Twilio SID for the messaging service to use for NANPA.
  #messagingServiceSid: # Twilio SID for the message service to use for non-NANPA.
  localDomain: signal.madecanggih.dev # Domain Twilio can connect back to for calls. Should be domain of your service.
  iosVerificationText: "verification code is - %s" # Text to use for the verification message on iOS. Will be passed to String.format with the verification code as argument 1.
  androidNgVerificationText: "verification code is - %s" # Text to use for the verification message on android-ng client types. Will be passed to String.format with the verification code as argument 1.
  android202001VerificationText: "verification code is - %s" # Text to use for the verification message on android-2020-01 client types. Will be passed to String.format with the verification code as argument 1.
  android202103VerificationText: "verification code is - %s" # Text to use for the verification message on android-2021-03 client types. Will be passed to String.format with the verification code as argument 1.
  genericVerificationText: "verification code is - %s" # Text to use when the client type is unrecognized. Will be passed to String.format with the verification code as argument 1.

push:
  queueSize: 200 # Size of push pending queue

turn: # TURN server configuration
  secret: secret# TURN server secret
  uris:
    - stun:signal.madecanggih.dev:3478
    - stun:signal.madecanggih.dev:5349
    - turn:signal.madecanggih.dev:3478?transport=udp
    - turn:signal.madecanggih.dev:5349?transport=udp

cacheCluster: # Redis server configuration for cache cluster
  urls:
    - redis://127.0.0.1:6379/

directory:
  client: # Configuration for interfacing with Contact Discovery Service cluster
    userAuthenticationTokenSharedSecret: ad2e341ca076657e34e4e29e3bfa6a86 # hex-encoded secret shared with CDS used to generate auth tokens for Signal users
    userAuthenticationTokenUserIdSecret: e9c3ed33d99073f48c7acc015f9821e6 # hex-encoded secret shared among Signal-Servers to obscure user phone numbers from CDS
  sqs:
    accessKey: AKIAIMF3IFW4TBQFB6JQ # AWS SQS accessKey
    accessSecret: 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  # AWS SQS accessSecret
    queueUrls:
      - https://sqs.ap-southeast-1.amazonaws.com/637423488741/chatqueue.fifo # AWS SQS queue url
  server:
    - replicationUrl: http://127.0.0.1:9090 # CDS replication endpoint base url
    - replicationPassword: password # CDS replication endpoint password
    - replicationCaCertificate: |
        -----BEGIN CERTIFICATE-----
        MIIF7zCCA9egAwIBAgIUUme0O2hOX+OWLwfKyIzgMFl4sjcwDQYJKoZIhvcNAQEL
        BQAwgYYxCzAJBgNVBAYTAklEMRQwEgYDVQQIDAtES0kgSmFrYXJ0YTEQMA4GA1UE
        BwwHSmFrYXJ0YTEPMA0GA1UECgwGVGVsa29tMQwwCgYDVQQLDANEZXYxEDAOBgNV
        BAMMB2NoYXRhcHAxHjAcBgkqhkiG9w0BCQEWD2RldkBleGFtcGxlLmNvbTAeFw0y
        MDAxMTAwODEzMzFaFw0yMTAxMDkwODEzMzFaMIGGMQswCQYDVQQGEwJJRDEUMBIG
        A1UECAwLREtJIEpha2FydGExEDAOBgNVBAcMB0pha2FydGExDzANBgNVBAoMBlRl
        bGtvbTEMMAoGA1UECwwDRGV2MRAwDgYDVQQDDAdjaGF0YXBwMR4wHAYJKoZIhvcN
        AQkBFg9kZXZAZXhhbXBsZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
        AoICAQCzGVGK0BM47gmPKE5DlNPuXIA/Jx+DdBMUhyt4AxxrtPBjbruVO05OMjcT
        qAXO+DatSQZT/K2/0oQACevrKIkBhXJwe4iUjWNb7nymntG8NKoQbByksYMTLXlj
        OrkPB9fOiGIFlNCZkFDdTkvMrjacjJvXtOMJMkc2UwUtNQ3ss5XLzVFx5J21Q3oo
        Ee1qnGJTUnmvOdCJHJzr7z7VdS6xeN6SOfmRPUi8LdKSbRG8KUcMPFMfMH1yvj6d
        eoTMPEuYq0Pm8j6yR7j+gHaRprlPAAPy9T7N5mN9Pdc7wDLo1qOr7TJ0PgLD641L
        o7uvS0u21tX2g/cR7cBzaEMV0XOJqh3LjHDlbJ1yUXXFSOLcLnXgmmrHL2HqTslF
        DDIh0ns8xG6iaI2CG7xHTJBfFhO0tA1yyUbivSQBRmJNozAPFTfOHtWNCesMJPFC
        x4FPp1iRQwBhAsJ3D80Fd+RNJH7WxP/ffEHPz2AbVqSSPdFjkI5xSqQLR5/k3bMa
        xGu7w0qQ7ifFYOEtETe+Xo1cUYbnheFPUoExxoRcWWl/42uTGsZazTlUo+LWH0yb
        xEB+MWmPREYqeCaoRIXV5UTsDlXjuQpRnIDl1xgdUkFTN6Trfn0eAUuRNM0bbQNL
        hDwCCLU4c2oY1mGgcXklxzOZIk5KQMFSMlOkVGhM6R2MmL1UWQIDAQABo1MwUTAd
        BgNVHQ4EFgQUBe0rUnGIOfQFvFcSzKB6HQhbCVYwHwYDVR0jBBgwFoAUBe0rUnGI
        OfQFvFcSzKB6HQhbCVYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
        AgEAmnb/xuo8AcqzL+cVnu+SSxHHJPPhMM7Bnm8ChFnw/CqeTRbxwa5Po7tj47CF
        ZH9NPpi3UEYGhAeyTcIPpa7mcgaIDoOrYA7Ku6BT2/KhlQu6vVg5xw3QBrnfplm+
        9VOnfKKoH7nD2lrW7rVZ/EZGzeChtI0AzCAlcnBQCnXziY5++LkWCzPmofHq+moP
        OAHyLMb3pUyPdCgTETLrrgNixrlb5s/rqTrwNe3XUo1YrPMTYzCN5mrCqQtOsvFp
        2L+y8RlfQ+AFJeQDCC6eUFYfK3Ls6qz7agm19EmyXO642M5eOdT4tobgt24YsnGx
        TupofOEbBU9F31LELSwe3bAu5N8RZvhay5C5u9ZrrUNlp1pr1Ljy0r51SmckmyY7
        4g8IT28E3cZhyFUsqwihxlwf9oHhxAzxOTVWiSobibc8r0q3hp3PutQFyPLRrfMf
        hDPTpUPm8v1rFRxNWXpe3w92y/iiJ53S4CWVmBIW9iKGqOyj7l2VEqe7KGKVO3Ma
        Z5b5jQMf6d2N1Qk2tt8YnL6EbT0mOJedhAfnkJl71UZzK7Lz1kLT+1MnlF+gazol
        vJiET6YNSW7sU/GNafapLfIqXU2wCfOFcrLEsW+DOEM2MLcY48ypPDcnwsl6OG+K
        qXeFHFld6v6s6pIGmc50pflU4qSJHAASDsUxw08xKxXnTtg=
        -----END CERTIFICATE-----
      # CDS replication endpoint TLS certificate trust root

messageCache: # Redis server configuration for message store cache
  #persistDelayMinutes:
  cluster:
    urls:
      - redis://127.0.0.1:6379/

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user:        postgres
  password:    postgres
  url:         jdbc:postgresql://127.0.0.1:5432/signal

metricsCluster:
  urls:
    - redis://127.0.0.1:6379/

awsAttachments: # AWS S3 configuration
  accessKey:    Q3AM3UQ867SPQQA43P2F
  accessSecret: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  bucket:       signal
  region:       us-east-1

gcpAttachments: # GCP Storage configuration
  domain: dummy.com
  email: dummy@dummy.com
  maxSizeInBytes: 1000000
  pathPrefix: /
  rsaSigningKey: "-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDwhYt8JjcT51v39xLoQmD7B6XCK5uF5Io0lBZjXN8y3z0NWN5+\nNZeujJ8quEG1B+8f81M65xEXTPIl1H9+XFZ2hhufYY6QPSq7sywxqjHgZvbk4eSv\nsxoB2OOngFCbBlrw6yJMprwIAgujX1RJB/VVuWQ8sMcc2zGIYLCdtzi2nQIDAQAB\nAoGBAMr1hdx/St7KzjqSDSxcRwXNUDxnG9eCIHV5uOKjzdxZsGUA5s7NXm92TiF4\nVknypf/qDgOYVD27OmJdzC/Or021uQzcagGixnTfLnc+Na/U6y8mL85h9Ky1cJsb\nWeDr3/CR7oYs1G+SHEZuQ7CnYl/NcTTv3x88QK+q3Ue3QUWpAkEA/jqpEfnS3CAE\nmSc55utpoRMwCHNGzt1ed8WWiuS+6XaBZeoLT3Dud9/uvDSnBZlrCSrr5k6nrQyw\n2FAn5nCYdwJBAPIycPw3Nm+3PDWQ1u4Np7WXGnPPi4ccyWcJYXpYxvyWFxhrwidx\noXnlOrG5KIIXJnOFqEuAp8nsdaNVG16DAosCQCgcUTiI1f/s/Uy8p6ILWmsTf+yV\nY4KX4qO7BPl9BbIIBHpz5rzt8HHxXtVK6V80yXJ01ytLFaFz8yLt4p20/hkCQQCQ\naIr9l14Z1kNMHQRKBFJO772R99nVwdBEY09/x5c927ABm560Lgh9ybPpa+E/T9ZZ\nYwQpoJhqyVaLAJ/FBpBpAkBQe1Av9I3bHXip3GmaIZqzKlKuW0VcO+3zJi5BBZHJ\n3sOCs8H491WHJOEuEkfOo3LK5q4aoNacLvyiUi0r6Iwl\n-----END RSA PRIVATE KEY-----\n"

profiles: # AWS S3 configuration
  accessKey:    Q3AM3UQ867SPQQA43P2F
  accessSecret: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  bucket:       signal
  region:       us-east-1

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user:        postgres
  password:    postgres
  url:         jdbc:postgresql://127.0.0.1:5432/signal

apn: # Apple Push Notifications configuration
  sandbox: true
  bundleId:
  keyId:
  teamId:
  signingKey:

gcm: # GCM Configuration
  senderId: 874271879526
  apiKey: AAAAy46qMWY:APA91bEe3gCLQIXRAXs8L6YITyt_2AP-d3k96s6j7-BQOqdvt03uad0fUivTZnvIMHWNrmRsnVFibjCB7QzlJ5iVKk9mQ9S_INx6MY4DxEnpz9SIcGOeaEnN09OV3tx6F9ZDMLRWfakB

micrometer: # Micrometer metrics config
  - name: "example"
  - uri: "https://metrics.example.com/"
  - apiKey: test
  - accountId: test

remoteConfig:
  authorizedTokens:
    - dummy
  globalConfig: dummy # keys and values that are given to clients on GET /v1/config

paymentService:
  userAuthenticationTokenSharedSecret: # hex-encoded 32-byte secret shared with MobileCoin services used to generate auth tokens for Signal users
  fixerApiKey: # api key
  paymentCurrencies:
    - USD